services:
  mysql:
    image: mysql:8.0
    container_name: vinaeatery_mysql
    restart: always
    environment:
      # MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: vinaeatery
      # MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    # volumes:
    #   - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    build: ./server
    container_name: vinaeatery_server
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_HOST: mysql
      SPRING_DATASOURCE_DATABASE: vinaeatery
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    ports:
      - "8080:8080"

  client:
    build: ./client
    container_name: vinaeatery_client
    depends_on:
      - server
    ports:
      - "5173:5173"

volumes:
  mysql_data: