server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: vinaeatery

  datasource:
    url: jdbc:mysql://${SPRING_DATASOURCE_HOST:localhost}:3306/${SPRING_DATASOURCE_DATABASE:vinaeatery}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
      generate_statistics: true

  servlet:
    multipart:
      enabled: true
      # default = 1MB
      max-file-size: 50MB
      # default = 10 MB (form data)
      max-request-size: 50MB

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  security:
    oauth2:
      client:
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=select_account
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          facebook:
            authorization-uri: https://www.facebook.com/v17.0/dialog/oauth
            token-uri: https://graph.facebook.com/v17.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
            user-name-attribute: id
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: email,profile
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/facebook
            scope: email,public_profile
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

  profiles:
    active: dev

jwt:
  base64-secret: ${JWT_SECRET}
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 86400

app:
  frontend_url: ${APP_DEV_FRONTEND_URL}
  backend_url: ${APP_DEV_BACKEND_URL}